name: update 163 news
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - run: pip install -r requirements.txt
      - shell: bash
        env:
          testfirst_password: ${{ secrets.TESTFIRST_PASSWORD }}
        run: |
          python main.py --service https://network.hukoubook.com --username testfirst.hukoubook.com --password "$testfirst_password"